name: "Sarif upload test."

on:
  pull_request:

jobs:
  sarif-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run script
        run: |
          npm ci
          npx --package=ts-node -y ts-node index.ts out.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: out.sarif
